### ISSUE TITLE
您好，请问已经上传了全部训练需要的代码了吗？

### ISSUE THREAD

**Issue by cxxPulsar** [njustkmg/NIC#1]
您好，请问已经上传了全部训练需要的代码了吗？我不能跑起来这个代码。感谢您的帮助！

**Comment by njustkmg** [comment]
Thank you for your question. After checking, the code for the method has been uploaded. The possible reason for not being able to train is the lack of the "cider" and "coco-caption" packages. You can install them or find them from the code of the AoANet project. The links to these packages have also been updated in the readme file. Please let me know if you have any other questions.
